# see https://github.com/hvr/multi-ghc-travis
env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.2

install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy-1.19.3
 - export PATH=/opt/happy/1.19.3/bin:/opt/ghc/$GHCVER/bin:$PATH
 - cabal-1.18 update

script:
 - cabal-1.18 sdist
 - cabal-1.18 install --enable-tests "dist/$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}')"
