# see https://github.com/hvr/multi-ghc-travis
env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.2

install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy-1.19.3
 - export PATH=/opt/happy/1.19.3/bin:/opt/ghc/$GHCVER/bin:$PATH
 - travis_retry cabal-1.18 update
 - travis_retry cabal-1.18 install --only-dependencies --enable-tests -v2

script:
 - cabal-1.18 build -v2 --enable-tests
 - cabal-1.18 test --show-details=always
 - cabal-1.18 sdist
 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
       cabal-1.18 install "$SRC_TGZ";
   else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
   fi
